# Generated by Django 5.2.5 on 2026-04-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logacaosistema',
            name='acao',
            field=models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW', 'Visualização'), ('ERROR', 'Erro')], max_length=20),
        ),
    ]
