# Generated by Django 5.2.5 on 2026-03-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalseger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='rota',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
