# Generated by Django 5.2.5 on 2026-03-25 19:47

import arquiteturaprocessos.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TiposDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'arquiteturaprocessos_tiposdocumento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('setor', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('funcao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_ativacaodesativacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_master', models.BooleanField(default=False, help_text='Usuário Master do sistema (invisível e não excluível)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arquiteturaprocessos.perfil')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LogAcaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW', 'Visualização'), ('ERROR', 'Erro')], max_length=20)),
                ('modelo_afetado', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField()),
                ('dados_antes', models.JSONField(blank=True, null=True)),
                ('dados_depois', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('sucesso', models.BooleanField(default=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_acao_sistema',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='MacroprocessoNivel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arquiteturaprocessos.classificacao')),
            ],
        ),
        migrations.CreateModel(
            name='MacroprocessoNivel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('macroprocesso_nivel1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arquiteturaprocessos.macroprocessonivel1')),
            ],
        ),
        migrations.CreateModel(
            name='ModelagemProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo', models.CharField(db_index=True, max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z0-9.\\-_/]+$')])),
                ('sequencial', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,4}$')])),
                ('versao', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)])),
                ('tema', models.CharField(db_index=True, max_length=150)),
                ('emitente', models.CharField(db_index=True, max_length=150)),
                ('sistema', models.CharField(db_index=True, max_length=100)),
                ('data_elaboracao', models.DateField(blank=True, null=True)),
                ('portaria_aprovacao', models.CharField(blank=True, max_length=150)),
                ('data_aprovacao', models.DateField(blank=True, null=True)),
                ('vigencia_inicio', models.DateField(blank=True, null=True)),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('link_normaprocedimento', models.URLField(blank=True, max_length=500, null=True)),
                ('documento_modelagem_processo', models.FileField(blank=True, max_length=500, null=True, upload_to=arquiteturaprocessos.models.mp_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelagens_criadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelagens_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelagens', to='arquiteturaprocessos.tiposdocumento')),
            ],
            options={
                'db_table': 'arquiteturaprocessos_modelagem_processo',
                'ordering': ['titulo', 'codigo', 'sequencial', 'versao', 'tema'],
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('gestor', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('objetivo', models.TextField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('area_responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('versao_processo', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Versão do Processo')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão do Processo')),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='arquiteturaprocessos.classificacao')),
                ('macroprocesso_nivel1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='macro_nivel1', to='arquiteturaprocessos.macroprocessonivel1')),
                ('macroprocesso_nivel2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='macro_nivel2', to='arquiteturaprocessos.macroprocessonivel2')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprocessos', to='arquiteturaprocessos.processo')),
                ('usuario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_atualizados', to=settings.AUTH_USER_MODEL)),
                ('usuario_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_cadastrados', to=settings.AUTH_USER_MODEL)),
                ('usuario_conclusao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_concluidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Conclusão')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'db_table': 'arquiteturaprocessos_processo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.CharField(blank=True, max_length=3, null=True)),
                ('numero', models.CharField(blank=True, max_length=9, null=True)),
                ('ramal', models.CharField(blank=True, max_length=5, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelagem_processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processo_documentos', to='arquiteturaprocessos.modelagemprocesso', verbose_name='Modelagem de Processo')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='arquiteturaprocessos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Documento do Processo',
                'verbose_name_plural': 'Documentos do Processo',
                'db_table': 'arquiteturaprocessos_processodocumento',
                'ordering': ['modelagem_processo__tipo_documento', 'modelagem_processo__titulo'],
                'constraints': [models.UniqueConstraint(fields=('processo', 'modelagem_processo'), name='unique_modelagem_por_processo')],
            },
        ),
        migrations.CreateModel(
            name='ProcessoMapear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('gestor', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('objetivo', models.TextField()),
                ('observacao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('area_responsavel', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('processo', 'Processo'), ('subprocesso', 'Subprocesso')], default='processo', max_length=20)),
                ('classificacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='arquiteturaprocessos.classificacao')),
                ('macroprocesso_nivel1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='arquiteturaprocessos.macroprocessonivel1')),
                ('macroprocesso_nivel2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='arquiteturaprocessos.macroprocessonivel2')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subprocessos_processomapear', to='arquiteturaprocessos.processo')),
                ('usuario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processosmapear_atualizados', to=settings.AUTH_USER_MODEL)),
                ('usuario_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processosmapear_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['nome'], name='arquitetura_nome_248971_idx'), models.Index(fields=['data_criacao'], name='arquitetura_data_cr_d0c314_idx'), models.Index(fields=['tipo'], name='arquitetura_tipo_ec2781_idx'), models.Index(fields=['tipo', 'macroprocesso_nivel1'], name='arquitetura_tipo_7895bc_idx'), models.Index(fields=['tipo', 'macroprocesso_nivel2'], name='arquitetura_tipo_d1ef13_idx')],
            },
        ),
    ]
