# Generated by Django 5.2.5 on 2025-10-22 13:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('setor', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('funcao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_ativacaodesativacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arquiteturaprocessos.perfil')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LogAcoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('area', models.CharField(max_length=100)),
                ('acao', models.CharField(max_length=100)),
                ('descricao_acao', models.TextField(max_length=500)),
                ('modelo_afetado', models.CharField(blank=True, max_length=100, null=True)),
                ('id_referencia', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MacroprocessoNivel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(max_length=500)),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='macroprocessos_nivel1', to='arquiteturaprocessos.classificacao')),
            ],
        ),
        migrations.CreateModel(
            name='MacroprocessoNivel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(max_length=500)),
                ('macroprocesso_nivel1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='macroprocessos_nivel2', to='arquiteturaprocessos.macroprocessonivel1')),
            ],
        ),
        migrations.CreateModel(
            name='ArquiteturaProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macroprocesso_nivel1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquiteturas_nivel1', to='arquiteturaprocessos.macroprocessonivel1')),
                ('macroprocesso_nivel2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquiteturas_nivel2', to='arquiteturaprocessos.macroprocessonivel2')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.CharField(blank=True, max_length=3, null=True)),
                ('numero', models.CharField(blank=True, max_length=9, null=True)),
                ('ramal', models.CharField(blank=True, max_length=5, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NormaProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(default='NORMA DE PROCEDIMENTO', max_length=200, verbose_name='Nome')),
                ('codigo', models.CharField(db_index=True, default='SRH', max_length=10, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9.\\-_/]+$', 'Use apenas letras, números e . - _ /')], verbose_name='Código')),
                ('sequencial', models.PositiveIntegerField(help_text='Número sequencial (1 a 999).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Sequencial')),
                ('versao', models.PositiveSmallIntegerField(help_text='Versão (1 a 99).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Versão')),
                ('tema', models.CharField(db_index=True, max_length=150, verbose_name='Tema')),
                ('emitente', models.CharField(db_index=True, max_length=150, verbose_name='Emitente')),
                ('sistema', models.CharField(db_index=True, max_length=100, verbose_name='Sistema')),
                ('data_elaboracao', models.DateField(blank=True, null=True, verbose_name='Data de Elaboração')),
                ('portaria_aprovacao', models.CharField(blank=True, max_length=150, verbose_name='Portaria de Aprovação')),
                ('data_aprovacao', models.DateField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('vigencia_inicio', models.DateField(blank=True, null=True, verbose_name='Início da Vigência')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='Fim da Vigência')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='Link')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normas_procedimento_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('usuario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normas_procedimento_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário (última atualização)')),
            ],
            options={
                'verbose_name': 'Norma de Procedimento',
                'verbose_name_plural': 'Normas de Procedimento',
                'db_table': 'norma_procedimento',
                'ordering': ['nome', 'codigo', 'sequencial', 'versao', 'tema'],
                'indexes': [models.Index(fields=['nome'], name='idx_np_nome'), models.Index(fields=['tema'], name='idx_np_tema'), models.Index(fields=['sistema'], name='idx_np_sistema'), models.Index(fields=['emitente'], name='idx_np_emitente')],
                'constraints': [models.UniqueConstraint(fields=('codigo', 'sequencial', 'versao'), name='uq_norma_proc_codigo_seq_versao')],
            },
        ),
    ]
