# Generated by Django 5.2.5 on 2025-12-09 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processodocumento',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='processodocumento',
            name='tipo_documento',
        ),
        migrations.AddField(
            model_name='processodocumento',
            name='modelagem_processo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='processo_documentos', to='arquiteturaprocessos.modelagemprocesso'),
            preserve_default=False,
        ),
    ]
