# Generated by Django 5.2.5 on 2025-11-14 19:07

import arquiteturaprocessos.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='norma',
        ),
        migrations.AddField(
            model_name='processo',
            name='modelagem_processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arquiteturaprocessos.modelagemprocesso', verbose_name='Modelagem de Processo'),
        ),
        migrations.AlterField(
            model_name='modelagemprocesso',
            name='documento_modelagem_processo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=arquiteturaprocessos.models.mp_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Documento de Modelagem de Processo'),
        ),
    ]
