# Generated by Django 5.2.5 on 2025-08-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogAtividade',
            new_name='LogAcoes',
        ),
    ]
