# Generated by Django 5.2.5 on 2025-10-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name="normaprocedimento",
                    table="arquiteturaprocessos_norma_procedimento",
                ),
            ],
            database_operations=[],
        ),
    ]

