# Generated by Django 5.2.5 on 2025-08-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0002_rename_logatividade_logacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='ddd',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='numero',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='ramal',
            field=models.CharField(max_length=5),
        ),
    ]
