# Generated by Django 5.2.5 on 2026-04-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0002_cria_log_acao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='nome',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='processomapear',
            name='nome',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='LogAcaoSistema',
        ),
    ]
