# Generated by Django 5.2.5 on 2025-11-17 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0002_remove_processo_norma_processo_modelagem_processo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='usuario_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que efetuou a última atualização'),
        ),
    ]
