# Generated by Django 5.2.5 on 2025-10-28 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0002_alinhar_tabela_norma_procedimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normaprocedimento',
            options={'managed': True, 'ordering': ['nome', 'codigo', 'sequencial', 'versao', 'tema'], 'verbose_name': 'Norma de Procedimento', 'verbose_name_plural': 'Normas de Procedimento'},
        ),
        migrations.AlterField(
            model_name='normaprocedimento',
            name='sequencial',
            field=models.CharField(help_text='Número sequencial (001 a 999).', max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,3}$', message='Informe um número válido entre 1 e 999 (sem letras ou símbolos).')], verbose_name='Sequencial'),
        ),
    ]
