# Generated by Django 5.2.5 on 2025-12-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0002_remove_processodocumento_documento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelagemprocesso',
            options={'ordering': ['titulo', 'codigo', 'sequencial', 'versao', 'tema']},
        ),
        migrations.RemoveField(
            model_name='modelagemprocesso',
            name='nome',
        ),
        migrations.AddField(
            model_name='modelagemprocesso',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
