# Generated by Django 5.2.5 on 2025-11-18 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0003_processo_usuario_atualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='emitente_modelo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Emitente do Modelo'),
        ),
        migrations.AddField(
            model_name='processo',
            name='emitente_norma',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Emitente da Norma'),
        ),
        migrations.AddField(
            model_name='processo',
            name='inicio_vigencia_modelo',
            field=models.DateField(blank=True, null=True, verbose_name='Início da Vigência do Modelo'),
        ),
        migrations.AddField(
            model_name='processo',
            name='inicio_vigencia_norma',
            field=models.DateField(blank=True, null=True, verbose_name='Início da Vigência da Norma'),
        ),
        migrations.AddField(
            model_name='processo',
            name='sistema_modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sistema do Modelo'),
        ),
        migrations.AddField(
            model_name='processo',
            name='sistema_norma',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sistema da Norma'),
        ),
        migrations.AddField(
            model_name='processo',
            name='tema_modelo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tema do Modelo'),
        ),
        migrations.AddField(
            model_name='processo',
            name='tema_norma',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tema da Norma'),
        ),
        migrations.AddField(
            model_name='processo',
            name='versao_modelo',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Versão do Modelo'),
        ),
        migrations.AddField(
            model_name='processo',
            name='versao_norma',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Versão da Norma'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='classificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='arquiteturaprocessos.classificacao', verbose_name='Classificação'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='macroprocesso_nivel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arquiteturaprocessos.macroprocessonivel1', verbose_name='Macroprocesso Nível 1'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='macroprocesso_nivel2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arquiteturaprocessos.macroprocessonivel2', verbose_name='Macroprocesso Nível 2'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='modelagem_processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arquiteturaprocessos.modelagemprocesso', verbose_name='Modelagem / Norma de Procedimento'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Processo'),
        ),
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['nome'], name='idx_processo_nome'),
        ),
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['gestor'], name='idx_processo_gestor'),
        ),
    ]
