# Generated by Django 5.2.5 on 2026-04-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0003_alter_processo_nome_alter_processomapear_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoAreaSeger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_area', models.CharField(max_length=255, unique=True, verbose_name='Nome da Área')),
                ('titular', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titular')),
                ('telefone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefone(s)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True)),
                ('origem', models.CharField(default='SEGER_SITE', max_length=100, verbose_name='Origem dos dados')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Contato Área SEGER',
                'verbose_name_plural': 'Contatos Área SEGER',
                'ordering': ['nome_area'],
            },
        ),
    ]
