# Generated by Django 5.2.5 on 2025-08-26 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0003_alter_telefone_ddd_alter_telefone_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefone',
            name='data_ativacaodesativacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
