# Generated by Django 5.2.5 on 2025-10-30 19:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0003_alter_normaprocedimento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normaprocedimento',
            options={'ordering': ['nome', 'codigo', 'sequencial', 'versao', 'tema'], 'verbose_name': 'Norma de Procedimento', 'verbose_name_plural': 'Normas de Procedimento'},
        ),
        migrations.AlterField(
            model_name='normaprocedimento',
            name='sequencial',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,3}$', message='Informe um número válido entre 1 e 999.')], verbose_name='Sequencial'),
        ),
        migrations.AlterField(
            model_name='normaprocedimento',
            name='versao',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Versão'),
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Processo/Subprocesso')),
                ('gestor', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('objetivo', models.TextField(verbose_name='Objetivo do Processo')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='arquiteturaprocessos.classificacao')),
                ('macroprocesso_nivel1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arquiteturaprocessos.macroprocessonivel1')),
                ('macroprocesso_nivel2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arquiteturaprocessos.macroprocessonivel2')),
                ('norma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arquiteturaprocessos.normaprocedimento')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprocessos', to='arquiteturaprocessos.processo')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processo / Subprocesso',
                'verbose_name_plural': 'Processos / Subprocessos',
                'db_table': 'arquiteturaprocessos_processo',
                'ordering': ['nome'],
            },
        ),
    ]
