# Generated by Django 5.2.5 on 2025-11-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0004_processo_emitente_modelo_processo_emitente_norma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='emitente_modelo',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='emitente_norma',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='inicio_vigencia_modelo',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='inicio_vigencia_norma',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='sistema_modelo',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='sistema_norma',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='tema_modelo',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='tema_norma',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='versao_modelo',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='versao_norma',
        ),
    ]
