# Generated by Django 5.2.5 on 2025-10-31 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0004_alter_normaprocedimento_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='processo',
            name='area_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Área Responsável'),
        ),
        migrations.AddField(
            model_name='processo',
            name='usuario_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que efetuou o cadastro'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='E-mail do Gestor'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='gestor',
            field=models.CharField(max_length=150, verbose_name='Gestor'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Processo/Subprocesso'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprocessos', to='arquiteturaprocessos.processo', verbose_name='Processo Pai'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone/Ramal'),
        ),
    ]
