# Generated by Django 5.2.5 on 2025-12-16 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0004_rename_tipodocumento_to_tiposdocumento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processo',
            options={'ordering': ['nome'], 'verbose_name': 'Processo', 'verbose_name_plural': 'Processos'},
        ),
        migrations.AlterModelOptions(
            name='processodocumento',
            options={'verbose_name': 'Documento do Processo', 'verbose_name_plural': 'Documentos do Processo'},
        ),
        migrations.AlterField(
            model_name='processo',
            name='area_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Área Responsável'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='classificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arquiteturaprocessos.classificacao', verbose_name='Classificação'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_atualizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='gestor',
            field=models.CharField(max_length=150, verbose_name='Gestor do Processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='macroprocesso_nivel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arquiteturaprocessos.macroprocessonivel1', verbose_name='Macroprocesso Nível 1'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='macroprocesso_nivel2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arquiteturaprocessos.macroprocessonivel2', verbose_name='Macroprocesso Nível 2'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='objetivo',
            field=models.TextField(verbose_name='Objetivo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprocessos', to='arquiteturaprocessos.processo', verbose_name='Processo Pai'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='usuario_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Atualização'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='usuario_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Cadastro'),
        ),
        migrations.AlterField(
            model_name='processodocumento',
            name='modelagem_processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processo_documentos', to='arquiteturaprocessos.modelagemprocesso', verbose_name='Modelagem de Processo'),
        ),
        migrations.AlterField(
            model_name='processodocumento',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='arquiteturaprocessos.processo', verbose_name='Processo'),
        ),
        migrations.AddConstraint(
            model_name='processodocumento',
            constraint=models.UniqueConstraint(fields=('processo', 'modelagem_processo'), name='unique_modelagem_por_processo'),
        ),
    ]
