# Generated by Django 5.2.5 on 2025-08-26 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0004_telefone_data_ativacaodesativacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefone',
            name='data_ativacaodesativacao',
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_ativacaodesativacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
