# Generated by Django 5.2.5 on 2026-04-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0004_contatoareaseger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processomapear',
            name='telefone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
