# Generated by Django 5.2.5 on 2026-04-10 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0005_alter_processo_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='area_responsavel_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='arquiteturaprocessos.contatoareaseger'),
        ),
        migrations.AddField(
            model_name='processomapear',
            name='area_responsavel_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_mapear', to='arquiteturaprocessos.contatoareaseger'),
        ),
    ]
