# Generated by Django 5.2.5 on 2025-12-17 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0005_alter_processo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processo',
            options={'ordering': ['nome'], 'verbose_name': 'Processo / Subprocesso', 'verbose_name_plural': 'Processos / Subprocessos'},
        ),
        migrations.AddField(
            model_name='processo',
            name='modelagem_processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_modelados', to='arquiteturaprocessos.modelagemprocesso', verbose_name='Modelo de Processo'),
        ),
        migrations.AddField(
            model_name='processo',
            name='norma_procedimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_norma', to='arquiteturaprocessos.modelagemprocesso', verbose_name='Norma de Procedimento'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='classificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='arquiteturaprocessos.classificacao', verbose_name='Classificação'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='E-mail do Gestor'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='gestor',
            field=models.CharField(max_length=150, verbose_name='Gestor'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='objetivo',
            field=models.TextField(verbose_name='Objetivo do Processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone/Ramal'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='usuario_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que efetuou a última atualização'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='usuario_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que efetuou o cadastro'),
        ),
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['nome'], name='idx_processo_nome'),
        ),
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['gestor'], name='idx_processo_gestor'),
        ),
    ]
