# Generated by Django 5.2.5 on 2025-08-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0005_remove_telefone_data_ativacaodesativacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='ddd',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='numero',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='ramal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='funcao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='setor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
