# Generated by Django 5.2.5 on 2025-11-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0005_remove_processo_emitente_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='data_atualizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Atualização'),
        ),
    ]
