# Generated by Django 5.2.5 on 2025-11-03 16:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0005_remove_processo_responsavel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaprocedimento',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='normaprocedimento',
            name='usuario_atualizacao',
        ),
        migrations.AlterField(
            model_name='processo',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprocessos', to='arquiteturaprocessos.processo', verbose_name='Processo Pai'),
        ),
        migrations.CreateModel(
            name='ModelagemProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(default='NORMA DE PROCEDIMENTO', max_length=200, verbose_name='Nome')),
                ('codigo', models.CharField(db_index=True, default='SRH', max_length=10, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9.\\-_/]+$', 'Use apenas letras, números e . - _ /')], verbose_name='Código')),
                ('sequencial', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,3}$', message='Informe um número válido entre 1 e 999.')], verbose_name='Sequencial')),
                ('versao', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Versão')),
                ('tema', models.CharField(db_index=True, max_length=150, verbose_name='Tema')),
                ('emitente', models.CharField(db_index=True, max_length=150, verbose_name='Emitente')),
                ('sistema', models.CharField(db_index=True, max_length=100, verbose_name='Sistema')),
                ('data_elaboracao', models.DateField(blank=True, null=True, verbose_name='Data de Elaboração')),
                ('portaria_aprovacao', models.CharField(blank=True, max_length=150, verbose_name='Portaria de Aprovação')),
                ('data_aprovacao', models.DateField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('vigencia_inicio', models.DateField(blank=True, null=True, verbose_name='Início da Vigência')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='Fim da Vigência')),
                ('link_normaprocedimento', models.URLField(blank=True, max_length=500, verbose_name='Link da Norma de Procedimento')),
                ('documento_modelagem_processo', models.FileField(blank=True, null=True, upload_to='modelagemprocessos/', verbose_name='Documento de Modelagem de Processo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelagens_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('usuario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelagens_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário (última atualização)')),
            ],
            options={
                'verbose_name': 'Modelagem de Processo',
                'verbose_name_plural': 'Modelagens de Processo',
                'db_table': 'arquiteturaprocessos_modelagem_processo',
                'ordering': ['nome', 'codigo', 'sequencial', 'versao', 'tema'],
            },
        ),
        migrations.AlterField(
            model_name='processo',
            name='norma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arquiteturaprocessos.modelagemprocesso', verbose_name='Norma de Procedimento'),
        ),
        migrations.AddIndex(
            model_name='modelagemprocesso',
            index=models.Index(fields=['nome'], name='idx_mp_nome'),
        ),
        migrations.AddIndex(
            model_name='modelagemprocesso',
            index=models.Index(fields=['tema'], name='idx_mp_tema'),
        ),
        migrations.AddIndex(
            model_name='modelagemprocesso',
            index=models.Index(fields=['sistema'], name='idx_mp_sistema'),
        ),
        migrations.AddIndex(
            model_name='modelagemprocesso',
            index=models.Index(fields=['emitente'], name='idx_mp_emitente'),
        ),
        migrations.AddConstraint(
            model_name='modelagemprocesso',
            constraint=models.UniqueConstraint(fields=('codigo', 'sequencial', 'versao'), name='uq_modelagem_codigo_seq_versao'),
        ),
        migrations.DeleteModel(
            name='NormaProcedimento',
        ),
    ]
