# Generated by Django 5.2.5 on 2025-11-05 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0006_remove_normaprocedimento_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelagemprocesso',
            name='documento_modelagem_processo',
            field=models.FileField(blank=True, null=True, upload_to='modelagemprocessos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Documento de Modelagem de Processo'),
        ),
        migrations.AlterField(
            model_name='modelagemprocesso',
            name='link_normaprocedimento',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link Norma de Procedimento'),
        ),
    ]
