# Generated by Django 5.2.5 on 2025-12-18 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0006_alter_processo_options_processo_modelagem_processo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processo',
            options={'ordering': ['nome'], 'verbose_name': 'Processo', 'verbose_name_plural': 'Processos'},
        ),
        migrations.AlterModelOptions(
            name='processodocumento',
            options={'ordering': ['modelagem_processo__tipo_documento', 'modelagem_processo__titulo'], 'verbose_name': 'Documento do Processo', 'verbose_name_plural': 'Documentos do Processo'},
        ),
        migrations.RemoveIndex(
            model_name='processo',
            name='idx_processo_nome',
        ),
        migrations.RemoveIndex(
            model_name='processo',
            name='idx_processo_gestor',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='modelagem_processo',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='norma_procedimento',
        ),
        migrations.AlterField(
            model_name='processo',
            name='classificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arquiteturaprocessos.classificacao', verbose_name='Classificação'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='gestor',
            field=models.CharField(max_length=150, verbose_name='Gestor do Processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='objetivo',
            field=models.TextField(verbose_name='Objetivo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='usuario_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Atualização'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='usuario_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Cadastro'),
        ),
    ]
