# Generated by Django 5.2.5 on 2025-11-28 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0006_alter_processo_data_atualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='norma_procedimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_norma', to='arquiteturaprocessos.modelagemprocesso', verbose_name='Norma de Procedimento'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='modelagem_processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_modelados', to='arquiteturaprocessos.modelagemprocesso', verbose_name='Modelo de Processo'),
        ),
    ]
