# Generated by Django 5.2.5 on 2026-04-10 19:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0006_processo_area_responsavel_fk_and_more'),
    ]

    operations = [

        migrations.AlterModelOptions(
            name='processo',
            options={},
        ),

        migrations.RemoveIndex(
            model_name='processomapear',
            name='arquitetura_nome_248971_idx',
        ),
        migrations.RemoveIndex(
            model_name='processomapear',
            name='arquitetura_data_cr_d0c314_idx',
        ),
        migrations.RemoveIndex(
            model_name='processomapear',
            name='arquitetura_tipo_ec2781_idx',
        ),
        migrations.RemoveIndex(
            model_name='processomapear',
            name='arquitetura_tipo_7895bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='processomapear',
            name='arquitetura_tipo_d1ef13_idx',
        ),

        # =========================
        # PROCESSO
        # =========================
        migrations.RemoveField(
            model_name='processo',
            name='area_responsavel',
        ),
        migrations.RenameField(
            model_name='processo',
            old_name='area_responsavel_fk',
            new_name='area_responsavel',
        ),

        # =========================
        # PROCESSOMAPEAR
        # =========================
        migrations.RemoveField(
            model_name='processomapear',
            name='area_responsavel',
        ),
        migrations.RenameField(
            model_name='processomapear',
            old_name='area_responsavel_fk',
            new_name='area_responsavel',
        ),

        # OUTROS CAMPOS
        migrations.AlterField(
            model_name='processo',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='usuario_conclusao',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='processos_concluidos',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='processo',
            name='versao_processo',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9999)
                ]
            ),
        ),

        migrations.AlterModelTable(
            name='processo',
            table=None,
        ),
    ]
