# Generated by Django 5.2.5 on 2025-11-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0007_alter_modelagemprocesso_documento_modelagem_processo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelagemprocesso',
            name='link_normaprocedimento',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Norma de Procedimento'),
        ),
    ]
