# Generated by Django 5.2.5 on 2026-04-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0007_alter_processo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processomapear',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('finalizado', 'Finalizado')], default='ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='processomapear',
            name='tipo',
            field=models.CharField(choices=[('processo', 'Processo'), ('subprocesso', 'Subprocesso'), ('outro', 'Outro')], default='processo', max_length=20),
        ),
    ]
