# Generated by Django 5.2.5 on 2025-10-01 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0007_classificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroprocessoNivel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='arquiteturaprocesso',
            name='macroprocesso_nivel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquiteturas_nivel1', to='arquiteturaprocessos.macroprocessonivel1'),
        ),
        migrations.CreateModel(
            name='MacroprocessoNivel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(max_length=500)),
                ('macroprocesso_nivel1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='macroprocessos_nivel2', to='arquiteturaprocessos.macroprocessonivel1')),
            ],
        ),
        migrations.AlterField(
            model_name='arquiteturaprocesso',
            name='macroprocesso_nivel2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquiteturas_nivel2', to='arquiteturaprocessos.macroprocessonivel2'),
        ),
        migrations.DeleteModel(
            name='Macroprocesso',
        ),
    ]
