# Generated by Django 5.2.5 on 2025-12-19 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0007_alter_processo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processo',
            options={},
        ),
        migrations.AlterField(
            model_name='processo',
            name='area_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='classificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='arquiteturaprocessos.classificacao'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_atualizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='gestor',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='processo',
            name='macroprocesso_nivel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arquiteturaprocessos.macroprocessonivel1'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='macroprocesso_nivel2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arquiteturaprocessos.macroprocessonivel2'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='processo',
            name='objetivo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='processo',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprocessos', to='arquiteturaprocessos.processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='usuario_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processo',
            name='usuario_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_cadastrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
