# Generated by Django 5.2.5 on 2025-11-28 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0007_processo_norma_procedimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='modelagem_processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_modelados', to='arquiteturaprocessos.modelagemprocesso', verbose_name='Modelo de Processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='norma_procedimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_norma', to='arquiteturaprocessos.modelagemprocesso', verbose_name='Norma de Procedimento'),
        ),
    ]
