# Generated by Django 5.2.5 on 2026-02-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0008_alter_processo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_master',
            field=models.BooleanField(default=False, help_text='Usuário Master do sistema (invisível e não excluível)'),
        ),
    ]
