# Generated by Django 5.2.5 on 2026-04-30 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0008_processomapear_status_alter_processomapear_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatoareaseger',
            name='usuario_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areasresponsaveis_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contatoareaseger',
            name='usuario_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areasresponsaveis_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contatoareaseger',
            name='origem',
            field=models.CharField(choices=[('SEGER_SITE', 'Importação SEGER'), ('MANUAL', 'Cadastro Manual')], default='SEGER_SITE', max_length=20, verbose_name='Origem dos dados'),
        ),
    ]
