# Generated by Django 5.2.5 on 2025-11-06 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0008_alter_modelagemprocesso_link_normaprocedimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelagemprocesso',
            name='documento_modelagem_processo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='modelagemprocessos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Documento de Modelagem de Processo'),
        ),
    ]
