# Generated by Django 5.2.5 on 2025-10-01 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0008_macroprocessonivel1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Macroprocesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nivel', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='arquiteturaprocesso',
            name='macroprocesso_nivel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquiteturas_nivel1', to='arquiteturaprocessos.macroprocesso'),
        ),
        migrations.AlterField(
            model_name='arquiteturaprocesso',
            name='macroprocesso_nivel2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquiteturas_nivel2', to='arquiteturaprocessos.macroprocesso'),
        ),
    ]
