# Generated by Django 5.2.5 on 2026-05-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0009_contatoareaseger_usuario_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatoareaseger',
            name='atualizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Atualizado em'),
        ),
    ]
