# Generated by Django 5.2.5 on 2026-02-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0009_usuario_is_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Usuário deve trocar a senha no próximo login'),
        ),
    ]
