# Generated by Django 5.2.5 on 2025-10-01 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0009_macroprocesso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquiteturaprocesso',
            name='macroprocesso_nivel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquiteturas_nivel1', to='arquiteturaprocessos.macroprocessonivel1'),
        ),
        migrations.AlterField(
            model_name='arquiteturaprocesso',
            name='macroprocesso_nivel2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquiteturas_nivel2', to='arquiteturaprocessos.macroprocessonivel2'),
        ),
        migrations.DeleteModel(
            name='Macroprocesso',
        ),
    ]
