# Generated by Django 5.2.5 on 2026-02-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0010_usuario_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='Usuário deve trocar a senha no próximo login'),
        ),
    ]
