# Generated by Django 5.2.5 on 2025-10-02 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0010_alter_arquiteturaprocesso_macroprocesso_nivel1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroprocessonivel1',
            name='classificacao',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, related_name='macroprocessos_nivel1', to='arquiteturaprocessos.classificacao'),
            preserve_default=False,
        ),
    ]
