# Generated by Django 5.2.5 on 2026-05-05 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0010_alter_contatoareaseger_atualizado_em'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS unaccent;",
            reverse_sql="DROP EXTENSION IF EXISTS unaccent;"
        ),
    ]
