# Generated by Django 5.2.5 on 2026-02-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0011_alter_usuario_must_change_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='must_change_password',
        ),
    ]
