# Generated by Django 5.2.5 on 2026-05-06 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0011_add_unaccent_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelagemprocesso',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9.\\-_/]+$')]),
        ),
        migrations.AlterField(
            model_name='modelagemprocesso',
            name='emitente',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='modelagemprocesso',
            name='portaria_aprovacao',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='modelagemprocesso',
            name='sequencial',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,4}$')]),
        ),
        migrations.AlterField(
            model_name='modelagemprocesso',
            name='sistema',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modelagemprocesso',
            name='tema',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='modelagemprocesso',
            name='titulo',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelagemprocesso',
            name='versao',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
