# Generated by Django 5.2.5 on 2026-02-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0012_remove_usuario_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacao',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='macroprocessonivel1',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='macroprocessonivel2',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tiposdocumento',
            name='descricao',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
