# Generated by Django 5.2.5 on 2026-05-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("arquiteturaprocessos", "0012_alter_modelagemprocesso_codigo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="macroprocessonivel1",
            options={
                "ordering": ["nome"],
            },
        ),
    ]