# Generated by Django 5.2.5 on 2026-05-22 16:44

import arquiteturaprocessos.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0012_alter_modelagemprocesso_codigo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='macroprocessonivel1',
            options={'ordering': ['nome']},
        ),
        migrations.CreateModel(
            name='ModeloProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(db_index=True, max_length=255, verbose_name='Título')),
                ('codigo', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Utilize apenas letras maiúsculas, números e . - _ /', regex='^[A-Z0-9.\\-_/]+$')], verbose_name='Código')),
                ('numero_modelo', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Informe apenas números.', regex='^\\d{1,10}$')], verbose_name='Número do Modelo')),
                ('versao', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Versão')),
                ('estado', models.CharField(choices=[('ELABORADO', 'Elaborado'), ('REVISADO', 'Revisado'), ('APROVADO', 'Aprovado')], db_index=True, default='ELABORADO', max_length=20, verbose_name='Estado')),
                ('setor', models.CharField(max_length=150, verbose_name='Setor')),
                ('unidades_envolvidas', models.TextField(blank=True, verbose_name='Unidades Envolvidas')),
                ('objetivo_processo', models.TextField(verbose_name='Objetivo do Processo')),
                ('abrangencia', models.TextField(blank=True, verbose_name='Abrangência')),
                ('fundamentacao_definicoes', models.TextField(blank=True, verbose_name='Fundamentação / Definições')),
                ('envolvidos_externos', models.TextField(blank=True, verbose_name='Envolvidos Externos')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('documento_modelo_processo', models.FileField(blank=True, max_length=500, null=True, upload_to=arquiteturaprocessos.models.modelo_processo_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Documento Modelo de Processo')),
                ('link_documento_externo', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Documento Externo')),
                ('data_elaboracao', models.DateTimeField(verbose_name='Data de Elaboração')),
                ('data_revisao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Revisão')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuario_aprovacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modelos_processo_aprovados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Aprovação')),
                ('usuario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modelos_processo_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Atualização')),
                ('usuario_elaboracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos_processo_elaborados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Elaboração')),
                ('usuario_revisao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modelos_processo_revisados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Revisão')),
            ],
            options={
                'verbose_name': 'Modelo de Processo',
                'verbose_name_plural': 'Modelos de Processo',
                'db_table': 'arquiteturaprocessos_modelo_processo',
                'ordering': ['-data_atualizacao', '-data_elaboracao'],
            },
        ),
    ]
