# Generated by Django 5.2.5 on 2026-02-23 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0013_alter_classificacao_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklogProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('gestor', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('objetivo', models.TextField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('area_responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('classificacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='arquiteturaprocessos.classificacao')),
                ('macroprocesso_nivel1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='arquiteturaprocessos.macroprocessonivel1')),
                ('macroprocesso_nivel2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='arquiteturaprocessos.macroprocessonivel2')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subprocessos_backlog', to='arquiteturaprocessos.processo')),
                ('usuario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backlogs_atualizados', to=settings.AUTH_USER_MODEL)),
                ('usuario_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backlogs_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['nome'], name='arquitetura_nome_c7b529_idx'), models.Index(fields=['classificacao'], name='arquitetura_classif_b09c3e_idx'), models.Index(fields=['macroprocesso_nivel1'], name='arquitetura_macropr_d18f20_idx'), models.Index(fields=['macroprocesso_nivel2'], name='arquitetura_macropr_937f8f_idx'), models.Index(fields=['parent'], name='arquitetura_parent__700931_idx'), models.Index(fields=['data_criacao'], name='arquitetura_data_cr_3daf5f_idx')],
            },
        ),
    ]
