# Generated by Django 5.2.5 on 2026-05-25 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0013_alter_macroprocessonivel1_options_modeloprocesso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeloprocesso',
            options={'ordering': ['-data_atualizacao', 'titulo', 'numero_modelo', 'versao'], 'verbose_name': 'Modelo de Processo', 'verbose_name_plural': 'Modelos de Processo'},
        ),
        migrations.AlterField(
            model_name='modeloprocesso',
            name='numero_modelo',
            field=models.CharField(db_index=True, max_length=8, validators=[django.core.validators.RegexValidator(message='Informe no formato 001/2025.', regex='^\\d{3}/\\d{4}$')], verbose_name='Número do Modelo'),
        ),
        migrations.AlterField(
            model_name='modeloprocesso',
            name='versao',
            field=models.CharField(db_index=True, default='0001', max_length=4, validators=[django.core.validators.RegexValidator(message='Informe a versão no formato 0001.', regex='^\\d{4}$')], verbose_name='Versão'),
        ),
        migrations.AddIndex(
            model_name='modeloprocesso',
            index=models.Index(fields=['titulo'], name='arquitetura_titulo_6dff64_idx'),
        ),
        migrations.AddIndex(
            model_name='modeloprocesso',
            index=models.Index(fields=['codigo'], name='arquitetura_codigo_8dbedd_idx'),
        ),
        migrations.AddIndex(
            model_name='modeloprocesso',
            index=models.Index(fields=['numero_modelo'], name='arquitetura_numero__4c4124_idx'),
        ),
        migrations.AddIndex(
            model_name='modeloprocesso',
            index=models.Index(fields=['estado'], name='arquitetura_estado_03340f_idx'),
        ),
    ]
