# Generated by Django 5.2.5 on 2026-07-02 13:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0013_alter_macroprocessonivel1_ordering_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemasUECI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sigla_sistema', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Sigla')),
                ('nome_sistema', models.CharField(max_length=200, unique=True, verbose_name='Nome do Sistema')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Sistema UECI',
                'verbose_name_plural': 'Sistemas UECI',
                'ordering': ['nome_sistema'],
            },
        ),
    ]
