# Generated by Django 5.2.5 on 2026-05-25 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0014_alter_modeloprocesso_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloprocesso',
            name='versao',
            field=models.CharField(db_index=True, default='0001', max_length=4, validators=[django.core.validators.RegexValidator(message='Informe a versão no formato 0001.', regex='^(?!0000)\\d{4}$')], verbose_name='Versão'),
        ),
    ]
