# Generated by Django 5.2.5 on 2026-02-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0014_backlogprocesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlogprocesso',
            name='area_responsavel',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backlogprocesso',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='backlogprocesso',
            name='gestor',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='backlogprocesso',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
