# Generated by Django 5.2.5 on 2026-07-06 19:31

import arquiteturaprocessos.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0014_sistemasueci'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormaProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nome_norma', models.CharField(db_index=True, max_length=255, verbose_name='Nome da Norma')),
                ('numero_norma', models.CharField(db_index=True, max_length=4, validators=[django.core.validators.RegexValidator(message='Informe no formato 0001.', regex='^(?!0000)\\d{4}$')], verbose_name='Nr. Norma')),
                ('versao', models.CharField(db_index=True, default='0001', max_length=4, validators=[django.core.validators.RegexValidator(message='Informe a versão no formato 0001.', regex='^(?!0000)\\d{4}$')], verbose_name='Versão')),
                ('emitente', models.CharField(db_index=True, max_length=255, verbose_name='Emitente')),
                ('data_elaboracao', models.DateField(verbose_name='Data Elaboração')),
                ('portaria_aprovacao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Portaria Aprovação')),
                ('data_aprovacao', models.DateField(blank=True, null=True, verbose_name='Data Aprovação')),
                ('vigencia_inicio', models.DateField(blank=True, null=True, verbose_name='Início Vigência')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='Fim Vigência')),
                ('documento_norma_procedimento', models.FileField(blank=True, max_length=500, null=True, upload_to=arquiteturaprocessos.models.norma_procedimento_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Documento Norma de Procedimento')),
                ('link_documento_norma', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link Documento Norma de Procedimento')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data Atualização')),
                ('sistema', models.ForeignKey(db_column='id_sistema', on_delete=django.db.models.deletion.PROTECT, related_name='normas_procedimento', to='arquiteturaprocessos.sistemasueci', verbose_name='Sistema')),
                ('usuario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='normas_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Atualização')),
                ('usuario_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Cadastro')),
            ],
            options={
                'verbose_name': 'Norma de Procedimento',
                'verbose_name_plural': 'Normas de Procedimento',
                'db_table': 'arquiteturaprocessos_norma_procedimento',
                'ordering': ['-data_atualizacao', 'nome_norma', 'numero_norma', 'versao'],
                'indexes': [models.Index(fields=['nome_norma'], name='arquitetura_nome_no_ea38a2_idx'), models.Index(fields=['sistema'], name='arquitetura_id_sist_68f399_idx'), models.Index(fields=['numero_norma'], name='arquitetura_numero__a0cccb_idx'), models.Index(fields=['emitente'], name='arquitetura_emitent_24fdce_idx')],
            },
        ),
    ]
