# Generated by Django 5.2.5 on 2026-05-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0015_alter_modeloprocesso_versao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloprocesso',
            name='data_elaboracao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Elaboração'),
        ),
    ]
