# Generated by Django 5.2.5 on 2026-02-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0015_alter_backlogprocesso_area_responsavel_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='backlogprocesso',
            name='arquitetura_nome_c7b529_idx',
        ),
        migrations.RemoveIndex(
            model_name='backlogprocesso',
            name='arquitetura_classif_b09c3e_idx',
        ),
        migrations.RemoveIndex(
            model_name='backlogprocesso',
            name='arquitetura_macropr_d18f20_idx',
        ),
        migrations.RemoveIndex(
            model_name='backlogprocesso',
            name='arquitetura_macropr_937f8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='backlogprocesso',
            name='arquitetura_parent__700931_idx',
        ),
        migrations.RemoveIndex(
            model_name='backlogprocesso',
            name='arquitetura_data_cr_3daf5f_idx',
        ),
    ]
