# Generated by Django 5.2.5 on 2026-07-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0015_normaprocedimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposdocumento',
            options={'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documento'},
        ),
        migrations.AddField(
            model_name='tiposdocumento',
            name='contexto',
            field=models.CharField(db_index=True, default='processo', max_length=15, verbose_name='Contexto'),
        ),
        migrations.AlterField(
            model_name='tiposdocumento',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tiposdocumento',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tiposdocumento',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
