# Generated by Django 5.2.5 on 2026-07-24 19:29

import arquiteturaprocessos.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0016_alter_tiposdocumento_options_tiposdocumento_contexto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processo',
            options={'ordering': ['-data_atualizacao', 'nome'], 'verbose_name': 'Processo', 'verbose_name_plural': 'Processos'},
        ),
        migrations.AlterModelOptions(
            name='processodocumento',
            options={'verbose_name': 'Norma de Procedimento do Processo', 'verbose_name_plural': 'Normas de Procedimento do Processo'},
        ),
        migrations.RemoveConstraint(
            model_name='processodocumento',
            name='unique_modelagem_por_processo',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='processodocumento',
            name='modelagem_processo',
        ),
        migrations.AddField(
            model_name='processo',
            name='abrangencia',
            field=models.CharField(choices=[('GOVES', 'GOVES'), ('SEGER', 'SEGER'), ('OUTROS', 'OUTROS')], default='GOVES', max_length=10, verbose_name='Abrangência'),
        ),
        migrations.AddField(
            model_name='processo',
            name='data_aprovacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Aprovação'),
        ),
        migrations.AddField(
            model_name='processo',
            name='data_elaboracao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Elaboração'),
        ),
        migrations.AddField(
            model_name='processo',
            name='documento_modelo_processo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=arquiteturaprocessos.models.modelo_processo_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Documento Modelo de Processo'),
        ),
        migrations.AddField(
            model_name='processo',
            name='link_documento_modelo_processo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Link Documento Modelo de Processo'),
        ),
        migrations.AddField(
            model_name='processo',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='processodocumento',
            name='norma_procedimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='arquiteturaprocessos.normaprocedimento', verbose_name='Norma de Procedimento'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_atualizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='gestor',
            field=models.CharField(max_length=150, verbose_name='Gestor'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='nome',
            field=models.CharField(max_length=500, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='objetivo',
            field=models.TextField(verbose_name='Objetivo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='telefone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='versao_processo',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Versão'),
        ),
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['nome'], name='idx_processo_nome'),
        ),
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['gestor'], name='idx_processo_gestor'),
        ),
        migrations.AddConstraint(
            model_name='processodocumento',
            constraint=models.UniqueConstraint(fields=('processo', 'norma_procedimento'), name='unique_norma_por_processo'),
        ),
        migrations.AlterModelTable(
            name='processo',
            table='arquiteturaprocessos_processo',
        ),
    ]
