# Generated by Django 5.2.5 on 2026-02-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0016_remove_backlogprocesso_arquitetura_nome_c7b529_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='backlogprocesso',
            index=models.Index(fields=['nome'], name='arquitetura_nome_c7b529_idx'),
        ),
        migrations.AddIndex(
            model_name='backlogprocesso',
            index=models.Index(fields=['data_criacao'], name='arquitetura_data_cr_3daf5f_idx'),
        ),
    ]
