# Generated by Django 5.2.5 on 2026-05-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0016_alter_modeloprocesso_data_elaboracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloprocesso',
            name='link_documento_externo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Link Documento Externo'),
        ),
    ]
