# Generated by Django 5.2.5 on 2026-07-24 19:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0017_alter_processo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='processodocumento',
            name='norma_procedimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='arquiteturaprocessos.normaprocedimento', verbose_name='Norma de Procedimento'),
        ),
    ]
