# Generated by Django 5.2.5 on 2026-05-29 17:36

import arquiteturaprocessos.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0017_alter_modeloprocesso_link_documento_externo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormaProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(db_index=True, max_length=255, verbose_name='Título')),
                ('sistema', models.CharField(db_index=True, max_length=100, verbose_name='Sistema')),
                ('sigla_sistema', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Utilize apenas letras maiúsculas, números e . - _ /', regex='^[A-Z0-9.\\-_/]+$')], verbose_name='Sigla Sistema')),
                ('numero_norma', models.CharField(db_index=True, max_length=4, validators=[django.core.validators.RegexValidator(message='Informe no formato 0001.', regex='^(?!0000)\\d{4}$')], verbose_name='Nr. Norma')),
                ('versao', models.CharField(db_index=True, default='0001', max_length=4, validators=[django.core.validators.RegexValidator(message='Informe a versão no formato 0001.', regex='^(?!0000)\\d{4}$')], verbose_name='Versão')),
                ('emitente', models.CharField(db_index=True, max_length=150, verbose_name='Emitente')),
                ('tema', models.CharField(db_index=True, max_length=150, verbose_name='Tema')),
                ('estado', models.CharField(choices=[('ELABORADO', 'Elaborado'), ('REVISADO', 'Revisado'), ('APROVADO', 'Aprovado'), ('PRESCRITO', 'Prescrito')], db_index=True, default='ELABORADO', max_length=20, verbose_name='Estado')),
                ('data_elaboracao', models.DateField(verbose_name='Data Elaboração')),
                ('portaria_aprovacao', models.CharField(blank=True, max_length=150, verbose_name='Portaria Aprovação')),
                ('data_aprovacao', models.DateField(blank=True, null=True, verbose_name='Data Aprovação')),
                ('vigencia_inicio', models.DateField(blank=True, null=True, verbose_name='Início Vigência')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='Fim Vigência')),
                ('documento_norma_procedimento', models.FileField(blank=True, max_length=500, null=True, upload_to=arquiteturaprocessos.models.norma_procedimento_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Documento Norma de Procedimento')),
                ('link_documento_externo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link Documento Externo')),
                ('data_revisao', models.DateTimeField(blank=True, null=True, verbose_name='Data Revisão')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data Atualização')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Cadastro')),
                ('usuario_aprovacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='normas_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Aprovação')),
                ('usuario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='normas_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Atualização')),
                ('usuario_elaboracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normas_elaboradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Elaboração')),
                ('usuario_revisao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='normas_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Revisão')),
            ],
            options={
                'verbose_name': 'Norma de Procedimento',
                'verbose_name_plural': 'Normas de Procedimento',
                'db_table': 'arquiteturaprocessos_norma_procedimento',
                'ordering': ['-data_atualizacao', 'titulo', 'numero_norma', 'versao'],
                'indexes': [models.Index(fields=['titulo'], name='arquitetura_titulo_f0769c_idx'), models.Index(fields=['sistema'], name='arquitetura_sistema_48811c_idx'), models.Index(fields=['sigla_sistema'], name='arquitetura_sigla_s_5062d0_idx'), models.Index(fields=['numero_norma'], name='arquitetura_numero__a0cccb_idx'), models.Index(fields=['tema'], name='arquitetura_tema_873238_idx'), models.Index(fields=['estado'], name='arquitetura_estado_d5bc16_idx')],
            },
        ),
    ]
