# Generated by Django 5.2.5 on 2026-02-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0017_backlogprocesso_arquitetura_nome_c7b529_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlogprocesso',
            name='tipo',
            field=models.CharField(choices=[('processo', 'Processo'), ('subprocesso', 'Subprocesso')], default='processo', max_length=20),
        ),
        migrations.AlterField(
            model_name='backlogprocesso',
            name='observacao',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='backlogprocesso',
            index=models.Index(fields=['tipo'], name='arquitetura_tipo_1084db_idx'),
        ),
        migrations.AddIndex(
            model_name='backlogprocesso',
            index=models.Index(fields=['tipo', 'macroprocesso_nivel1'], name='arquitetura_tipo_972866_idx'),
        ),
        migrations.AddIndex(
            model_name='backlogprocesso',
            index=models.Index(fields=['tipo', 'macroprocesso_nivel2'], name='arquitetura_tipo_23619b_idx'),
        ),
    ]
