# Generated by Django 5.2.5 on 2026-03-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0018_backlogprocesso_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlogprocesso',
            name='data_atualizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
