# Generated by Django 5.2.5 on 2026-06-03 14:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0018_normaprocedimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normaprocedimento',
            old_name='usuario',
            new_name='usuario_cadastro',
        ),
        migrations.AddField(
            model_name='modeloprocesso',
            name='data_cadastro',
            field=models.DateTimeField(
                auto_now_add=True,
                verbose_name='Data Cadastro'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modeloprocesso',
            name='usuario_cadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos_processo_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Cadastro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modeloprocesso',
            name='data_aprovacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Aprovação'),
        ),
        migrations.AlterField(
            model_name='modeloprocesso',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data Atualização'),
        ),
        migrations.AlterField(
            model_name='modeloprocesso',
            name='data_elaboracao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Elaboração'),
        ),
        migrations.AlterField(
            model_name='modeloprocesso',
            name='data_revisao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Revisão'),
        ),
        migrations.AlterField(
            model_name='normaprocedimento',
            name='data_revisao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Revisão'),
        ),
    ]
