# Generated by Django 5.2.5 on 2026-07-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0018_alter_processo_uuid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processo',
            options={'ordering': ['-data_atualizacao', '-data_criacao', 'nome'], 'verbose_name': 'Processo', 'verbose_name_plural': 'Processos'},
        ),
    ]
