# Generated by Django 5.2.5 on 2026-08-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0019_alter_processo_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelagemProcesso',
        ),
    ]
