# Generated by Django 5.2.5 on 2026-07-03 19:47

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        (
            "arquiteturaprocessos",
            "0020_sistemasueci",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="normaprocedimento",
            old_name="titulo",
            new_name="nome_norma",
        ),
    ]