# Generated by Django 5.2.5 on 2026-08-14 12:12

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preencher_uuids_processos_mapear(apps, schema_editor):
    """
    Gera um UUID único para cada registro existente de ProcessoMapear.

    Esta etapa é necessária porque o campo UUID está sendo introduzido
    em uma tabela que já possui registros.
    """
    ProcessoMapear = apps.get_model(
        "arquiteturaprocessos",
        "ProcessoMapear"
    )

    for processo_mapear in ProcessoMapear.objects.filter(
        uuid__isnull=True
    ):
        processo_mapear.uuid = uuid.uuid4()
        processo_mapear.save(
            update_fields=["uuid"]
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "arquiteturaprocessos",
            "0020_delete_modelagemprocesso"
        ),
    ]

    operations = [

        # ========================================================
        # ABRANGÊNCIA
        # ========================================================
        migrations.AddField(
            model_name="processomapear",
            name="abrangencia",
            field=models.CharField(
                choices=[
                    ("GOVES", "GOVES"),
                    ("SEGER", "SEGER"),
                    ("OUTROS", "OUTROS"),
                ],
                default="GOVES",
                max_length=10,
                verbose_name="Abrangência",
            ),
        ),

        # ========================================================
        # DATA DE FINALIZAÇÃO
        # ========================================================
        migrations.AddField(
            model_name="processomapear",
            name="data_finalizacao",
            field=models.DateTimeField(
                blank=True,
                null=True,
            ),
        ),

        # ========================================================
        # RESPONSÁVEL PELA FINALIZAÇÃO
        # ========================================================
        migrations.AddField(
            model_name="processomapear",
            name="usuario_finalizacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processosmapear_finalizados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        # ========================================================
        # UUID – ETAPA 1
        #
        # Campo temporariamente permite NULL e não possui
        # UNIQUE. Isso permite adicionar o campo em uma tabela
        # que já possui registros.
        # ========================================================
        migrations.AddField(
            model_name="processomapear",
            name="uuid",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="UUID",
            ),
        ),

        # ========================================================
        # UUID – ETAPA 2
        #
        # Gera um UUID individual para cada registro existente.
        # ========================================================
        migrations.RunPython(
            preencher_uuids_processos_mapear,
            reverse_code=migrations.RunPython.noop,
        ),

        # ========================================================
        # UUID – ETAPA 3
        #
        # Agora que todos os registros existentes possuem UUID
        # individual, podemos aplicar a definição definitiva
        # do campo.
        # ========================================================
        migrations.AlterField(
            model_name="processomapear",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]