# Generated by Django 5.2.5 on 2026-03-05 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0020_rename_backlogprocesso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processo',
            options={'ordering': ['nome'], 'verbose_name': 'Processo', 'verbose_name_plural': 'Processos'},
        ),
        migrations.AddField(
            model_name='processo',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão do Processo'),
        ),
        migrations.AddField(
            model_name='processo',
            name='usuario_conclusao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_concluidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Conclusão'),
        ),
        migrations.AddField(
            model_name='processo',
            name='versao_processo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Versão do Processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='macroprocesso_nivel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='macro_nivel1', to='arquiteturaprocessos.macroprocessonivel1'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='macroprocesso_nivel2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='macro_nivel2', to='arquiteturaprocessos.macroprocessonivel2'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='processomapear',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subprocessos_processomapear', to='arquiteturaprocessos.processo'),
        ),
        migrations.AlterField(
            model_name='processomapear',
            name='usuario_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processosmapear_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processomapear',
            name='usuario_cadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processosmapear_criados', to=settings.AUTH_USER_MODEL),
        ),
    ]
