# Generated by Django 5.2.5 on 2026-08-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0021_processomapear_abrangencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='imagem',
            field=models.ImageField(max_length=500,blank=True, null=True, upload_to='classificacoes/'),
        ),
    ]
