# Generated by Django 5.2.5 on 2026-07-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0021_rename_titulo_para_nome_norma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normaprocedimento',
            options={'ordering': ['-data_atualizacao', 'nome_norma', 'numero_norma', 'versao'], 'verbose_name': 'Norma de Procedimento', 'verbose_name_plural': 'Normas de Procedimento'},
        ),
        migrations.RemoveIndex(
            model_name='normaprocedimento',
            name='arquitetura_titulo_f0769c_idx',
        ),
        migrations.AlterField(
            model_name='normaprocedimento',
            name='nome_norma',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nome da Norma'),
        ),
        migrations.AddIndex(
            model_name='normaprocedimento',
            index=models.Index(fields=['nome_norma'], name='arquitetura_nome_no_ea38a2_idx'),
        ),
    ]
