# Generated by Django 5.2.5 on 2026-03-13 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0021_alter_processo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelagemprocesso',
            name='codigo',
            field=models.CharField(db_index=True, max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z0-9.\\-_/]+$')]),
        ),
        migrations.AlterField(
            model_name='modelagemprocesso',
            name='sequencial',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,4}$')]),
        ),
        migrations.AlterField(
            model_name='modelagemprocesso',
            name='versao',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='processo',
            name='versao_processo',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Versão do Processo'),
        ),
    ]
