# Generated by Django 5.2.5 on 2026-03-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0022_rename_arquitetura_nome_c7b529_idx_arquitetura_nome_248971_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='processomapear',
            new_name='arquitetura_nome_248971_idx',
            old_name='arquitetura_nome_c7b529_idx',
        ),
        migrations.RenameIndex(
            model_name='processomapear',
            new_name='arquitetura_data_cr_d0c314_idx',
            old_name='arquitetura_data_cr_3daf5f_idx',
        ),
        migrations.RenameIndex(
            model_name='processomapear',
            new_name='arquitetura_tipo_ec2781_idx',
            old_name='arquitetura_tipo_1084db_idx',
        ),
        migrations.RenameIndex(
            model_name='processomapear',
            new_name='arquitetura_tipo_7895bc_idx',
            old_name='arquitetura_tipo_972866_idx',
        ),
        migrations.RenameIndex(
            model_name='processomapear',
            new_name='arquitetura_tipo_d1ef13_idx',
            old_name='arquitetura_tipo_23619b_idx',
        ),
    ]
