# Generated by Django 5.2.5 on 2026-08-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0022_classificacao_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='imagem_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
    ]
