# Generated by Django 5.2.5 on 2026-07-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0022_alter_normaprocedimento_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='normaprocedimento',
            name='arquitetura_sigla_s_5062d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='normaprocedimento',
            name='arquitetura_tema_873238_idx',
        ),
        migrations.RemoveIndex(
            model_name='normaprocedimento',
            name='arquitetura_estado_d5bc16_idx',
        ),
        migrations.RemoveField(
            model_name='normaprocedimento',
            name='data_revisao',
        ),
        migrations.RemoveField(
            model_name='normaprocedimento',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='normaprocedimento',
            name='sigla_sistema',
        ),
        migrations.RemoveField(
            model_name='normaprocedimento',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='normaprocedimento',
            name='usuario_aprovacao',
        ),
        migrations.RemoveField(
            model_name='normaprocedimento',
            name='usuario_elaboracao',
        ),
        migrations.RemoveField(
            model_name='normaprocedimento',
            name='usuario_revisao',
        ),
        migrations.AddIndex(
            model_name='normaprocedimento',
            index=models.Index(fields=['emitente'], name='arquitetura_emitent_24fdce_idx'),
        ),
    ]
