# Generated by Django 5.2.5 on 2026-08-27 14:16

import arquiteturaprocessos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0023_classificacao_imagem_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacao',
            name='imagem',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=arquiteturaprocessos.models.nome_imagem_classificacao),
        ),
    ]
