# Generated by Django 5.2.5 on 2026-07-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0023_remove_normaprocedimento_arquitetura_sigla_s_5062d0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaprocedimento',
            name='emitente',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Emitente'),
        ),
    ]
