# Generated by Django 5.2.5 on 2026-09-02 17:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0024_alter_classificacao_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemCadeiaValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, max_length=3000, verbose_name='Descrição')),
                ('imagem', models.ImageField(upload_to='cadeia_valor/', verbose_name='Imagem')),
                ('situacao', models.CharField(choices=[('Ativa', 'Ativa'), ('Inativa', 'Inativa')], db_index=True, default='Inativa', max_length=7, verbose_name='Situação')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data Inclusão')),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data Atualização')),
                ('data_ativacao', models.DateTimeField(blank=True, null=True, verbose_name='Data Ativação')),
                ('data_desativacao', models.DateTimeField(blank=True, null=True, verbose_name='Data Desativação')),
                ('responsavel_ativacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagem_cadeia_valor_ativadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Ativação')),
                ('responsavel_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagem_cadeia_valor_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Atualização')),
                ('responsavel_desativacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagem_cadeia_valor_desativadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Desativação')),
                ('responsavel_inclusao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagem_cadeia_valor_incluidas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Inclusão')),
            ],
            options={
                'verbose_name': 'Imagem da Cadeia de Valor',
                'verbose_name_plural': 'Imagens da Cadeia de Valor',
                'db_table': 'arquiteturaprocessos_imagem_cadeia_valor',
                'ordering': ['-data_inclusao'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('situacao', 'Ativa')), fields=('situacao',), name='unique_imagem_cadeia_valor_ativa')],
            },
        ),
    ]
