# Generated by Django 5.2.5 on 2026-09-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0025_imagemcadeiavalor'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='ordem',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Ordem'),
        ),
    ]
