# Generated by Django 5.2.5 on 2026-09-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0027_preencher_ordem_classificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacao',
            name='ordem',
            field=models.PositiveIntegerField(db_index=True, unique=True, verbose_name='Ordem'),
        ),
    ]
