# Generated by Django 5.2.5 on 2026-09-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0028_alter_classificacao_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaprocedimento',
            name='norma_exclusiva',
            field=models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Exclusiva'),
        ),
    ]
