# Generated by Django 5.2.5 on 2026-10-01 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0033_seed_funcionalidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FuncionalidadeAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionalidades', to='arquiteturaprocessos.acao')),
                ('funcionalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='arquiteturaprocessos.funcionalidade')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('funcionalidade', 'acao'), name='unique_funcionalidade_acao')],
            },
        ),
    ]
