# Generated by Django 5.2.5 on 2026-10-02 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0036_seed_funcionalidade_acoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionalidade_acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_perfil', to='arquiteturaprocessos.funcionalidadeacao')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='arquiteturaprocessos.perfil')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('perfil', 'funcionalidade_acao'), name='unique_perfil_permissao')],
            },
        ),
    ]
