# Generated by Django 5.2.5 on 2026-10-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0037_perfilpermissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='protegido',
            field=models.BooleanField(default=False),
        ),
    ]
