# Generated by Django 5.2.5 on 2026-10-06 19:50

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquiteturaprocessos', '0042_ajusta_ordem_funcionalidades_administracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='perfil',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='unique_perfil_nome_lower'),
        ),
    ]
